#! /bin/bash

# Lint files as Verilog-2001, finding submodules as needed in the current directory

ALL_FILES=$@

for FILE in ${ALL_FILES}
do
    verilator -Wall +1364-2001ext+v -y . --lint-only ${FILE}
done

